# Generated by Django 3.2.9 on 2021-12-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.CharField(max_length=225)),
                ('productId', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=225)),
                ('StorageQuantity', models.IntegerField()),
                ('PricePerUnit', models.IntegerField()),
                ('img', models.CharField(max_length=225)),
            ],
        ),
    ]
