# Generated by Django 3.2.9 on 2021-12-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Desc',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(max_length=225, upload_to=''),
        ),
    ]
